version: "3.3"
services:
  api:
    networks:
      - server-network
    image: alexay7/yomiyasu-back
    depends_on:
      - "mongodb"
      - "cache"
    environment:
      - ACCESS_SECRET=valor_del_access_secret
      - REFRESH_SECRET=valor_del_refresh_secret
      - REDIS_HOST=cache
      - MONGOURL=mongodb://mongodb:27017/yomiyasu
    volumes:
      - type: bind
        source: /folder/with/book/library
        target: /usr/src/exterior
      - type: bind
        source: /config/folder/dicts
        target: /usr/src/dicts
  cache:
    image: redis:6.2-alpine
    restart: always
    networks:
      - server-network
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=4096
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  client:
    depends_on:
      - "api"
    networks:
      - server-network
    image: alexay7/yomiyasu-front
    ports:
      - "PORT:80"
  mongodb:
    image: mongo:4.4.22
    networks:
      - server-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: /config/folder/db
        target: /data/db
    restart: unless-stopped
networks:
  server-network:
volumes:
  cache:
    driver: local
